QUERY_KEYS_MAP = {
    "all_words": {"map_key": "q", "available_countries": ("ALL",)},
    "age": {"map_key": "fromage", "available_countries": ("AU", "GB", "CA", "US")},
    "posted_by": {
        "map_key": "sc=0bf%3{0}",
        "available_countries": ("AU", "GB"),
        "items": {"Employer": "Aexrec()", "Staffing Agency": "Aexdh()"},
    },
    "remote": {
        "map_key_short": "attr({0})",
        "map_key": "sc=0kf%3Aattr({0})",
        "available_countries": ("AU", "GB", "CA", "US"),
        "items": {
            "Remote": "DSQF7",
            "Temporarily Remote": "VAMUB",
            "Hybrid remote": "PAXZC",
        },
    },
    "location": {"map_key": "l", "available_countries": ("AU", "GB", "US", "CA")},
    "radius": {"map_key": "radius", "available_countries": ("AU", "GB", "US", "CA")},
    "salary_estimate": {
        "map_key": "q",
        "available_countries": ("AU", "GB", "CA", "US"),
    },
    "jobs_type": {"map_key": "jt", "available_countries": ("AU", "GB", "CA", "US")},
    "education_level": {
        "map_key_short": "attr({0})",
        "map_key": "sc=0kf%3Aattr({0})",
        "available_countries": ("AU", "GB", "US"),
        "items": {
            "Bachelor's degree": "HFDVW",
            "Master's degree": "EXSNN",
            "Diploma": "RTWUW",
            "Doctoral degree": "6QC5F",
            "Certificate III": "CESAH",
            "Certificate IV": "A3EGS",
            "High School (Year 12)": "FCGTU",
            "Certificate II": "KXWRV",
            "Certificate I": "ZZMB5",
            "GCSE": "AC9NV",
            "A Level": "FCGTU",
            "Certificate of higher education": "HFPJM",
            "Diploma of higher education": "UTPWG",
            "Foundation degree": "C25GV",
        },
    },
    "education": {
        "map_key_short": "attr({0})",
        "map_key": "sc=0kf%3Aattr({0})",
        "available_countries": ("US",),
        "items": {
            "Bachelor's degree": "FCGTU%7CHFDVW%7CQJZM9%7CUTPWG%252COR",
            "Master's degree": "EXSNN%7CFCGTU%7CHFDVW%7CQJZM9%7CUTPWG%252COR",
            "Doctoral degree": "6QC5F%252COR",
            "Associate's Degree": "FCGTU%7CQJZM9%7CUTPWG%252COR",
            "High School Degree": "FCGTU%7CQJZM9%252COR",
        },
    },
    "display": {"map_key": "limit", "available_countries": ("AU", "GB", "CA", "US")},
    "relevance": {"map_key": "sort", "available_countries": ("AU", "GB", "CA", "US")},
    "industry": {
        "map_key_short": "cmpsec({0})",
        "map_key": "sc=0kf%3Acmpsec({0})",
        "available_countries": ("GB", "CA"),
        "items": {
            "Human Resources & Staffing": "Q3FC3",
            "Healthcare": "22VKN",
            "Retail & Wholesale": "48BZP",
            "Education": "RFWNN",
            "Finance": "MSQWR",
            "Information Technology": "NKR5F",
            "Construction Repair & Maintenance Services": "NTW8X",
            "Restaurants & Food Service": "W2F4E",
            "Management & Consulting": "92AZY",
            "Media & Communication": "4DGEF",
            "Manufacturing": "CPGHF",
            "Real Estate": "S7KHR",
            "Hotel & Travel Accommodation": "X42V4",
            "Transportation & Logistics": "P634J",
            "Telecommunications": "JGU5R",
            "Legal": "6GW2X",
            "Insurance": "4EWFJ",
            "Non-profit & NGO": "ZMM32",
            "Energy Mining Utilities": "TAN6J",
            "Government & Public Administration": "B23RH",
            "Pharmaceutical & Biotechnology": "5ZM33",
            "Arts Entertainment & Recreation": "N322U",
            "Personal Consumer Services": "ZYCW4",
            "Aerospace & Defence": "HV5U6",
            "Agriculture": "SVBZF",
        },
    },
    "occupation": {
        "map_key_short": "occ({0})",
        "map_key": "sc=0kf%3Aocc({0})",
        "available_countries": ("CA",),
        "items": {
            "Sales Retail & Customer Support Occupations": "NTGY4",
            "Food & Beverage Occupations": "NPKCD",
            "Technology Occupations": "EHPW9",
            "Organization Operations & Administrative Occupations": "MGTWW",
            "Healthcare Occupations": "CFV7X",
            "Education & Instruction Occupations": "AB5HX",
            "Construction & Extraction Occupations": "SZ69B",
            "Supply Chain & Logistics Occupations": "TVT66",
            "Transportation Occupations": "CKA43",
            "Repair Maintenance & Installation Occupations": "YAQ96",
            "Manufacturing & Utilities Occupations": "6XYW3",
            "Community & Social Services Occupations": "BCMJX",
            "Marketing Advertising & Public Relations Occupations": "W83QK",
            "Finance & Accounting Occupations": "6YCJB",
            "Architecture & Engineering Occupations": "HY4VD",
            "Science & Research Occupations": "585N6",
            "Personal Service Occupations": "DSCP2",
            "Safety Security & Civil Defence Occupations": "HNQ6F",
            "Cleaning & Grounds Maintenance Occupations": "67D4Z",
            "Travel Attractions & Events Occupations": "FYPW9",
            "Media Arts & Design Occupations": "SWYS8",
            "Legal Occupations": "W727U",
            "Farming Fisheries & Forestry Occupations": "5FNC8",
        },
    },
    "job_language": {"map_key": "lang", "available_countries": ("CA",)},
    "experience_level": {
        "map_key_short": "explvl({0})",
        "map_key": "sc=0kf%3Aexplvl({0})",
        "available_countries": ("US",),
        "items": {
            "Entry Level": "ENTRY_LEVEL",
            "Mid Level": "MID_LEVEL",
            "Senior Level": "SENIOR_LEVEL",
        },
    },
}
